#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const DATA = path.join(ROOT, "data");

function readJson(name) {
  return JSON.parse(fs.readFileSync(path.join(DATA, name), "utf8"));
}

function assert(cond, msg) {
  if (!cond) throw new Error(msg);
}

/**
 * Readings a child should never meet as the default, found by COMPUTATION.
 *
 * This used to be a hand-written list of three characters that only warned —
 * and its 行 rule carried `skipIfEn: /row|.../`, which suppressed the warning
 * for exactly the defective row (`háng` "row") it was meant to catch. Three
 * entries against 1,599 words, one of them self-defeating.
 *
 * The replacement compares every served reading against the curated story
 * dictionary — the lexicon assembled from already-validated sources, which the
 * child actually reads — and fails on a disagreement. That is a real oracle:
 * it caught 27 rows the hand list did not, among them 听 as `yǐn`
 * "smile (archaic)", 读 as `dòu` "comma" and 鸟 as `diǎo`, an obscenity.
 *
 * Entries below are the reviewed exceptions: places the two sources differ for
 * a good reason. Anything not listed here must agree.
 */
const READING_EXCEPTIONS = {
  // The dictionary glosses in context; the curriculum teaches the base word.
  "妈": "the story reads 妈妈; the taught character is mā",
  "爸": "the story reads 爸爸; the taught character is bà",
  // Both readings are ordinary and the row's own pos backs the served one.
  "干": "gàn (to do) is verb-first, as this row's pos says",
  "只": "zhǐ (only) is adverb-first, as this row's pos says",
  "头": "tóu (head) is noun-first, as this row's pos says",
  "种": "zhǒng (kind/type) is the measure-word reading this row is tagged for",
  "子": "zi as a word ending; the story gloss and the curriculum agree in sense",
};

function loadCuratedDictionary() {
  try {
    const built = require("./story-dictionary.js").build();
    return built.dict || built;
  } catch (e) {
    return null;   // the dictionary needs the story corpus; skip rather than fail
  }
}

const normPy = (p) => String(p || "").toLowerCase().normalize("NFC").replace(/\s+/g, "");

/**
 * Dictionary artefacts that must never be a beginner's default meaning.
 * The curriculum was generated by taking whichever CC-CEDICT sense came first,
 * which for common characters is often the surname or an abbreviation — so 水
 * was taught as "surname Shui". Repaired by scripts/repair_vocab.js; this stops
 * it coming back.
 */
const JUNK_GLOSS = /variant of|abbr\./i;
const JUNK_GLOSS_STRICT = /^\s*(surname |old variant of|used in )/i;
const OVERRIDES = (() => { try { return require("./vocab-overrides.js"); } catch (e) { return {}; } })();

const CURATED = loadCuratedDictionary();

/**
 * Senses that are dictionary machinery, not a meaning a ten-year-old can use.
 * Kept in step with ARTEFACT_SENSE in scripts/build_hsk_curriculum.js: what the
 * builder refuses to emit is what this refuses to accept.
 */
const ARTEFACT_SENSE = /\(chess\)|archaic|^\s*comma\s*$|first month of the lunar year|\bradical\b|^\(of (a|an) [a-z]+\)|dozen \(loanword\)/i;

/**
 * One served row against the curated dictionary and the artefact list.
 *
 * The comparison is COMPUTED here from the two data sources, not looked up in a
 * table of known-bad rows — a list of the defects we already found cannot catch
 * the next one, which is how the previous three-entry version missed 27.
 */
function checkReading(zh, py, en, where, problems) {
  if (ARTEFACT_SENSE.test(en)) {
    problems.push(`${where} is glossed "${en}" — a specialist or archaic sense, not a beginner's default`);
  }
  if (!CURATED || READING_EXCEPTIONS[zh]) return;
  const entry = CURATED[zh];
  if (!entry || !entry.py) return;
  if (normPy(entry.py) !== normPy(py)) {
    problems.push(
      `${where} is read "${py}" but the curated story dictionary reads it "${entry.py}" ` +
      `("${en}" vs "${entry.en}") — a child would hear one and see the other`
    );
  }
}

function checkVocabQuality(doc, name, problems) {
  const seen = (w, where) => {
    const en = String(w.en || "");
    const py = String(w.pinyin || w.py || "").trim();
    if (!en.trim()) problems.push(`${where}: ${w.zh} has no English meaning`);
    if (JUNK_GLOSS.test(en) || JUNK_GLOSS_STRICT.test(en)) {
      problems.push(`${where}: ${w.zh} is glossed "${en.slice(0, 40)}" — a dictionary artefact, not a meaning`);
    }
    // Half of a longer word's English. The story and lesson validators grew this
    // check after 211 such glosses turned up in the reader; the gate vocabulary
    // was still teaching 地 as "-ly" and 超级 as "super-", which a child meets in
    // the games and the quizzes rather than the reader.
    const t = en.trim();
    if (/^[-—]/.test(t) || /^[A-Za-z.]+-$/.test(t)) {
      problems.push(`${where}: ${w.zh} is glossed "${t}" — a fragment of a longer word's English, not a meaning`);
    }
    if (/^[A-Z]{2,5}$/.test(t)) {
      problems.push(`${where}: ${w.zh} is glossed "${t}" — a grammar code; say what it does in plain words`);
    }
    // A gloss that TRAILS a hyphen is rejected by isCleanMeaning, so the word is
    // silently dropped from every word pool built from a story — it simply stops
    // being taught. 非 "not; non-" and 再 "again; once more; re-" both vanished
    // that way. Say the meaning without the prefix form.
    if (/-$/.test(t)) {
      problems.push(`${where}: ${w.zh} is glossed "${t}" — a trailing hyphen drops it from the word pools`);
    }
    const allowedProper = OVERRIDES[w.zh] && OVERRIDES[w.zh].proper;
    if (/^[A-Z]/.test(py) && !allowedProper) {
      problems.push(`${where}: ${w.zh} has proper-noun pinyin "${py}" — a surname reading displacing the common word`);
    }
  };
  (doc.words || []).forEach((w) => seen(w, `${name}.words`));
  (doc.gates || []).forEach((g) => {
    (g.newWords || []).forEach((w) => seen(w, `${name}.gate${g.gateId}.newWords`));
    (g.reviewWords || []).forEach((w) => seen(w, `${name}.gate${g.gateId}.reviewWords`));
  });
}

function checkLevel(doc, name, problems) {
  // The level's size is no longer a magic 300: the ordinary-vocabulary
  // supplement grew each level, and pinning the constant here is what would
  // make adding a word look like a validation failure. The invariants that
  // matter are that the three counts AGREE and that nothing is duplicated.
  const total = doc.words.length;
  assert(total > 0, `${name}: no words`);
  assert(doc.totalWords === total, `${name}: totalWords ${doc.totalWords} != words ${total}`);
  assert(Array.isArray(doc.gates) && doc.gates.length === 22, `${name}: gates must be 22`);
  const uniq = new Set(doc.words.map((w) => w.zh));
  assert(uniq.size === total, `${name}: duplicate zh found inside level`);
  const gateSum = doc.gates.reduce((a, g) => a + ((g.newWords && g.newWords.length) || 0), 0);
  assert(gateSum === total, `${name}: gate newWords sum ${gateSum} != words ${total}`);
  const gateWords = new Set();
  for (const g of doc.gates) for (const w of g.newWords || []) gateWords.add(w.zh);
  assert(gateWords.size === total, `${name}: gates teach ${gateWords.size} distinct words, level lists ${total}`);

  for (const w of doc.words) {
    const py = (w.pinyin || w.py || "").trim();
    const en = String(w.en || "");
    // U+FFFD means text was decoded wrongly somewhere upstream. 并 "bìng"
    // shipped to children as "b\ufffd\ufffdng" in three places because the
    // curriculum fetch concatenated HTTP chunks without setting an encoding,
    // splitting a multi-byte character. Nothing caught it.
    for (const [field, val] of [["zh", w.zh], ["pinyin", py], ["en", en]]) {
      assert(!String(val).includes("\uFFFD"),
        `${name}: ${w.zh} has a corrupted ${field} "${val}" — decoded with the wrong encoding`);
    }

    checkReading(w.zh, py, en, `${name}: ${w.zh}`, problems);
  }

  // The same defective row is copied into its gate's newWords and the next two
  // gates' reviewWords, so report each character once rather than four times —
  // the count should say how many words are wrong, not how many copies exist.
  const seenInGates = new Set();
  for (const g of doc.gates) {
    for (const field of ["newWords", "reviewWords"]) {
      for (const w of g[field] || []) {
        if (seenInGates.has(w.zh)) continue;
        seenInGates.add(w.zh);
        const py = (w.pinyin || w.py || "").trim();
        const en = String(w.en || "");
        checkReading(w.zh, py, en, `${name} gates: ${w.zh}`, problems);
      }
    }
  }
}

function main() {
  const h1 = readJson("hsk1.json");
  const h2 = readJson("hsk2.json");
  const h3 = readJson("hsk3.json");
  const h4 = readJson("hsk4.json");
  const culture = readJson("culture_stories.json");

  const problems = [];
  checkLevel(h1, "hsk1", problems);
  checkLevel(h2, "hsk2", problems);
  checkLevel(h3, "hsk3", problems);
  checkLevel(h4, "hsk4", problems);

  const borrowed = h2.words.filter((w) => w.sourceTag === "HSK3_borrowed_for_HSK2").length;
  assert(borrowed === 103, `hsk2: borrowed words must be 103, got ${borrowed}`);

  assert(Array.isArray(culture.tracks), "culture_stories: tracks must be array");
  const allStories = culture.tracks.flatMap((t) => (Array.isArray(t.stories) ? t.stories : []));
  const solarTrack = culture.tracks.find((t) => t.id === "solar_terms_24");
  assert(!!solarTrack, "culture_stories: solar_terms_24 track missing");
  const solar = (solarTrack.stories || []).length;
  assert(solar === 24, `culture_stories: expected 24 solar terms, got ${solar}`);
  assert(allStories.length >= 29, `culture_stories: expected at least 29 stories, got ${allStories.length}`);
  const familyRewardOK = culture.rewardCatalog.familyRewardTypes.includes("ask_parents_help");
  assert(familyRewardOK, "culture_stories: ask_parents_help reward missing");

  [[h1, "hsk1"], [h2, "hsk2"], [h3, "hsk3"], [h4, "hsk4"]].forEach(([doc, name]) => {
    checkVocabQuality(doc, name, problems);
  });
  if (problems.length) {
    problems.slice(0, 20).forEach((p) => console.error(`  FAIL  ${p}`));
    if (problems.length > 20) console.error(`  ... and ${problems.length - 20} more`);
    throw new Error(`${problems.length} vocabulary quality problem(s)`);
  }

  console.log("Curriculum validation passed.");
}

main();
