#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const DATA = path.join(ROOT, "data");

function readJson(name) {
  return JSON.parse(fs.readFileSync(path.join(DATA, name), "utf8"));
}

function assert(cond, msg) {
  if (!cond) throw new Error(msg);
}

/** Common kid-track homographs: warn if pinyin/en look like a less-common reading. */
const HOMOGRAPH_WARN = [
  { zh: "都", badPy: /^dū/i, hint: "prefer dōu (all/both) for learners" },
  {
    zh: "还",
    badPy: /^huán/i,
    hint: "hái (still/also) vs huán (return); check gloss matches pinyin",
  },
  {
    zh: "行",
    badPy: /^háng/i,
    skipIfEn: /row|line|bank|industry|walk\s*of|surname/i,
    hint: "xíng (OK/walk) vs háng (row); check gloss matches pinyin",
  },
];

/**
 * Dictionary artefacts that must never be a beginner's default meaning.
 * The curriculum was generated by taking whichever CC-CEDICT sense came first,
 * which for common characters is often the surname or an abbreviation — so 水
 * was taught as "surname Shui". Repaired by scripts/repair_vocab.js; this stops
 * it coming back.
 */
const JUNK_GLOSS = /variant of|abbr\./i;
const JUNK_GLOSS_STRICT = /^\s*(surname |old variant of|used in )/i;
const OVERRIDES = (() => { try { return require("./vocab-overrides.js"); } catch (e) { return {}; } })();

function checkVocabQuality(doc, name, problems) {
  const seen = (w, where) => {
    const en = String(w.en || "");
    const py = String(w.pinyin || w.py || "").trim();
    if (!en.trim()) problems.push(`${where}: ${w.zh} has no English meaning`);
    if (JUNK_GLOSS.test(en) || JUNK_GLOSS_STRICT.test(en)) {
      problems.push(`${where}: ${w.zh} is glossed "${en.slice(0, 40)}" — a dictionary artefact, not a meaning`);
    }
    const allowedProper = OVERRIDES[w.zh] && OVERRIDES[w.zh].proper;
    if (/^[A-Z]/.test(py) && !allowedProper) {
      problems.push(`${where}: ${w.zh} has proper-noun pinyin "${py}" — a surname reading displacing the common word`);
    }
  };
  (doc.words || []).forEach((w) => seen(w, `${name}.words`));
  (doc.gates || []).forEach((g) => {
    (g.newWords || []).forEach((w) => seen(w, `${name}.gate${g.gateId}.newWords`));
    (g.reviewWords || []).forEach((w) => seen(w, `${name}.gate${g.gateId}.reviewWords`));
  });
}

function checkLevel(doc, name) {
  assert(doc.totalWords === 300, `${name}: totalWords must be 300`);
  assert(Array.isArray(doc.words) && doc.words.length === 300, `${name}: words must be 300`);
  assert(Array.isArray(doc.gates) && doc.gates.length === 22, `${name}: gates must be 22`);
  const uniq = new Set(doc.words.map((w) => w.zh));
  assert(uniq.size === 300, `${name}: duplicate zh found inside level`);
  const gateSum = doc.gates.reduce((a, g) => a + ((g.newWords && g.newWords.length) || 0), 0);
  assert(gateSum === 300, `${name}: gate newWords sum must be 300`);

  for (const w of doc.words) {
    const py = (w.pinyin || w.py || "").trim();
    const en = String(w.en || "");
    for (const rule of HOMOGRAPH_WARN) {
      if (w.zh !== rule.zh) continue;
      if (rule.skipIfEn && rule.skipIfEn.test(en)) continue;
      if (rule.badPy && rule.badPy.test(py)) {
        console.warn(`${name}: homograph audit — ${rule.zh} pinyin "${py}" / "${en}" (${rule.hint})`);
      }
    }
  }

  for (const g of doc.gates) {
    for (const field of ["newWords", "reviewWords"]) {
      for (const w of g[field] || []) {
        const py = (w.pinyin || w.py || "").trim();
        const en = String(w.en || "");
        for (const rule of HOMOGRAPH_WARN) {
          if (w.zh !== rule.zh) continue;
          if (rule.skipIfEn && rule.skipIfEn.test(en)) continue;
          if (rule.badPy && rule.badPy.test(py)) {
            console.warn(
              `${name} gate ${g.gateId} ${field}: homograph audit — ${rule.zh} pinyin "${py}" / "${en}" (${rule.hint})`
            );
          }
        }
      }
    }
  }
}

function main() {
  const h1 = readJson("hsk1.json");
  const h2 = readJson("hsk2.json");
  const h3 = readJson("hsk3.json");
  const h4 = readJson("hsk4.json");
  const culture = readJson("culture_stories.json");

  checkLevel(h1, "hsk1");
  checkLevel(h2, "hsk2");
  checkLevel(h3, "hsk3");
  checkLevel(h4, "hsk4");

  const borrowed = h2.words.filter((w) => w.sourceTag === "HSK3_borrowed_for_HSK2").length;
  assert(borrowed === 103, `hsk2: borrowed words must be 103, got ${borrowed}`);

  assert(Array.isArray(culture.tracks), "culture_stories: tracks must be array");
  const allStories = culture.tracks.flatMap((t) => (Array.isArray(t.stories) ? t.stories : []));
  const solarTrack = culture.tracks.find((t) => t.id === "solar_terms_24");
  assert(!!solarTrack, "culture_stories: solar_terms_24 track missing");
  const solar = (solarTrack.stories || []).length;
  assert(solar === 24, `culture_stories: expected 24 solar terms, got ${solar}`);
  assert(allStories.length >= 29, `culture_stories: expected at least 29 stories, got ${allStories.length}`);
  const familyRewardOK = culture.rewardCatalog.familyRewardTypes.includes("ask_parents_help");
  assert(familyRewardOK, "culture_stories: ask_parents_help reward missing");

  const problems = [];
  [[h1, "hsk1"], [h2, "hsk2"], [h3, "hsk3"], [h4, "hsk4"]].forEach(([doc, name]) => {
    checkVocabQuality(doc, name, problems);
  });
  if (problems.length) {
    problems.slice(0, 20).forEach((p) => console.error(`  FAIL  ${p}`));
    if (problems.length > 20) console.error(`  ... and ${problems.length - 20} more`);
    throw new Error(`${problems.length} vocabulary quality problem(s)`);
  }

  console.log("Curriculum validation passed.");
}

main();
